version: "3.8"
services:
  turnej-server:
    build:
      context: ./server
    depends_on:
      - turnej-db
    ports:
      - "3001:3001"
    container_name: turnej-server
    volumes:
      - ./server:/usr/src/turnej/server
      - /usr/src/turnej/server/node_modules
  turnej-db:
    image: postgres:13
    restart: always
    container_name: turnej-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: turnej
    ports:
      - "5432:5432"
    volumes:
      - ./db/init/create.sql:/docker-entrypoint-initdb.d/1-create.sql
      - ./db/seeds/basic-seed.sql:/docker-entrypoint-initdb.d/2-basic-seed.sql
